apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  labels:
    app: todo
    tier: frontend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
      tier: frontend 
  template:
    metadata:
      labels:
        app: todo
        tier: frontend 
    spec:
      containers:
      - name: todo-frontend 
        image: 637423610157.dkr.ecr.us-east-1.amazonaws.com/cwc-frontend-ecr:latest
        ports:
        - containerPort: 80
