apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-job
spec:
  template:
    spec:
      containers:
      - name: database-migration
        image: 637423610157.dkr.ecr.us-east-1.amazonaws.com/cwc-api-ecr:latest
        env:
        - name: DB_HOST
          value: {{.Values.database.host}}
        - name: DB_USERNAME
          value: {{.Values.database.username}}
        - name: DB_PASSWORD
          value: {{.Values.database.password}}
        - name: ENVIRONMENT
          value: {{.Values.environment}}
        command: ["npm",  "run", "migration:run"]
      restartPolicy: Never
  backoffLimit: 1

