name: Deploy
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps: 
        - name: Configure AWS Credentials 
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}
        - name: Log into AWS ECR
          id: login-aws-ecr
          uses: aws-actions/amazon-ecr-login@v2
          with:
            region: ${{ secrets.AWS_REGION }}
        - name: Deploy to EC2
          run: |
            command_id=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-079b8a960de1eb7e7,i-03e076b90fc93fcb1" \
            --comment "Pull Docker image and run it" \
            --parameters 'commands=[
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}",
              "docker pull ${{ steps.login-aws-ecr.outputs.registry}}/${{secrets.AWS_ECR_REPO}}:latest",
              "docker run --rm -d -p 3000:3000 --name api ${{ steps.login-aws-ecr.outputs.registry}}/${{secrets.AWS_ECR_REPO}}:latest"
              ]' \
            --query 'Command.CommandId' \
            --output text)

            aws ssm wait command-executed \
            --command-id $command_id \
            --instance-id i-079b8a960de1eb7e7 || true 

            aws ssm wait command-executed \
            --command-id $command_id \
            --instance-id i-03e076b90fc93fcb1 || true 

            status=$(aws ssm list-command-invocations \
            --command-id $command_id \
            --details \
            --query "CommandInvocations[0].StatusDetails" \
            --output text)

            if [ "$status" == "Success" ]; then
              echo "Command executed successfully"
            else 
              echo "Command failed"
              aws ssm list-command-invocations --command-id $command_id --details
              exit 1
            fi
